# Activation Function


# Importing Libraries

In [1]:
from numpy import array #For Array Initialization
from numpy import random #For Randomly choosing Numbers
from numpy import dot #For Doing DOT Product
from random import choice

# Initialized Dataset

In [2]:
dataset = [
    (array([0,0,1]), 0), #array([x,y,b],e) x,y=Input , b=bias, e=Expected O/P to validate
    (array([0,1,1]), 1),
    (array([1,0,1]), 1),
    (array([1,1,1]), 1),
]
print(dataset)
print(array([0,0,1]), 0)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]
[0 0 1] 0


# Initializing Random numbers for WEIGHTS

In [3]:
weights = random.rand(3)
weights

array([0.20614247, 0.67361084, 0.76030004])

# Initializing additional variables

In [4]:
r = 0.2 #learning Rate
n = 100 #Number of Iteration

# ACTIVATION FUNCTION

# Training & Evaluating using STEP Activation Function

In [5]:
activationFn = lambda x: 0 if x < 0 else 1 #step activation function (if i/p is negative o/p is 0 else 1)
for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x)
    err = expected-activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

ResultBAFn: -0.04 ResultAFn: 0
ResultBAFn: 0.634 ResultAFn: 1
ResultBAFn: 0.166 ResultAFn: 1
ResultBAFn: 0.84 ResultAFn: 1


# Training & Evaluating using LINEAR Activation Function


In [6]:
activationFn = lambda x: x 

for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x) 
    err = expected-activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

ResultBAFn: 0.211 ResultAFn: 0.21074703041747608
ResultBAFn: 0.648 ResultAFn: 0.6479160056882081
ResultBAFn: 0.634 ResultAFn: 0.6337467158571406
ResultBAFn: 1.071 ResultAFn: 1.0709156911278725


# Training & Evaluating using SIGMOID Activation Function

In [8]:
import numpy as np
activationFn = lambda x: 1/(1+np.exp(-x))
error = []
for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x) 
    err = expected-activationFn(result)
    error.append(err)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

ResultBAFn: -0.089 ResultAFn: 0.47768211964440943
ResultBAFn: 1.768 ResultAFn: 0.8542027356319372
ResultBAFn: 1.863 ResultAFn: 0.8656050074759278
ResultBAFn: 3.72 ResultAFn: 0.976337756390945


# Training & Evaluating using RELU Activation Function

In [9]:
activationFn = lambda x: 0 if x < 0 else x 
for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x)
    err = expected-activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

ResultBAFn: 0.167 ResultAFn: 0.16724610188002245
ResultBAFn: 0.941 ResultAFn: 0.9412932525348069
ResultBAFn: 0.851 ResultAFn: 0.8507162290388112
ResultBAFn: 1.625 ResultAFn: 1.6247633796935956


# Training & Evaluating using SOFTMAX Activation Function

In [10]:
activationFn = lambda x: np.exp(x) / np.sum(np.exp(x), axis=0)
err = []
for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x) 
    err = expected-activationFn(result)
    error.append(err)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

ResultBAFn: -4.833 ResultAFn: 1.0
ResultBAFn: -4.059 ResultAFn: 1.0
ResultBAFn: -4.149 ResultAFn: 1.0
ResultBAFn: -3.375 ResultAFn: 1.0
